import { FormEvent, useState } from 'react'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Input } from '../components/ui/Input'
import { useAdminData } from '../hooks/useAdminData'
import { useAuth } from '../hooks/useAuth'
import { AdminMaterial, AdminMiembro, AdminPerfil, createMaterial, createMiembro, createPerfil, deleteMaterial, deleteMiembro, deletePerfil, MaterialInput, MiembroInput, updateMaterial, updateMiembro, updatePerfil } from '../services/adminService'

type Detail = { key: string; value: string }
const blankMaterial: MaterialInput = { titulo: '', tipo: 'Libro', estado: 'Disponible', detalles_extra: {} }
const blankMiembro: MiembroInput = { nombre_completo: '', tipo: '', codigo: '', contacto: '' }
const blankPerfil: { id: string; nombre: string; rol: 'Administrador' | 'Bibliotecario' } = { id: '', nombre: '', rol: 'Bibliotecario' }

export function AdminPage() {
  const { perfil, signOut } = useAuth()
  const data = useAdminData()
  const [message, setMessage] = useState('')
  const [actionError, setActionError] = useState('')
  async function mutate(messageText: string, action: () => Promise<void>) {
    setMessage(''); setActionError('')
    try { await action(); await data.refresh(); setMessage(messageText) } catch { setActionError('No pudimos guardar el cambio. Revise los datos e inténtelo nuevamente.') }
  }
  return <main className="mx-auto max-w-7xl px-5 py-6 sm:px-8">
    <header className="flex flex-col gap-4 border-b-4 border-brand-blue pb-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="m-0 font-bold text-brand-blue">Sistema de Biblioteca</p><h1 className="mt-1 text-3xl font-extrabold">Administración</h1><p className="m-0 text-slate-700">Gestione catálogo, miembros y personal.</p></div><Button variant="secondary" onClick={() => signOut()}>Cerrar sesión</Button></header>
    {(data.error || actionError || message) && <div className={`mt-6 rounded-lg border-2 p-4 font-semibold ${data.error || actionError ? 'border-danger bg-red-50 text-danger' : 'border-success bg-green-50 text-success'}`} role={data.error || actionError ? 'alert' : 'status'}>{data.error || actionError || message}</div>}
    {data.isLoading ? <AdminSkeleton /> : <div className="mt-6 space-y-8"><MaterialManager items={data.materiales} mutate={mutate} /><MiembroManager items={data.miembros} mutate={mutate} /><PerfilManager items={data.perfiles} ownId={perfil?.id ?? ''} mutate={mutate} /></div>}
  </main>
}

type Mutate = (message: string, action: () => Promise<void>) => Promise<void>
function MaterialManager({ items, mutate }: { items: AdminMaterial[]; mutate: Mutate }) {
  const [editing, setEditing] = useState<AdminMaterial | null>(null); const [form, setForm] = useState<MaterialInput>(blankMaterial); const [details, setDetails] = useState<Detail[]>([{ key: '', value: '' }])
  const reset = () => { setEditing(null); setForm(blankMaterial); setDetails([{ key: '', value: '' }]) }
  const beginEdit = (item: AdminMaterial) => { setEditing(item); setForm({ titulo: item.titulo, tipo: item.tipo, estado: item.estado, detalles_extra: item.detalles_extra ?? {} }); const rows = Object.entries(item.detalles_extra ?? {}).map(([key, value]) => ({ key, value: typeof value === 'string' ? value : JSON.stringify(value) })); setDetails(rows.length ? rows : [{ key: '', value: '' }]) }
  const submit = async (event: FormEvent) => { event.preventDefault(); const json: Record<string, unknown> = {}; details.filter((row) => row.key.trim()).forEach(({ key, value }) => { try { json[key.trim()] = JSON.parse(value) } catch { json[key.trim()] = value } }); const input = { ...form, detalles_extra: json }; await mutate(editing ? 'Material actualizado correctamente.' : 'Material creado correctamente.', () => editing ? updateMaterial(editing.id, input) : createMaterial(input)); reset() }
  return <Card aria-labelledby="materiales-title"><Title id="materiales-title" text="Gestión de materiales" description="Campos principales y datos adicionales del catálogo." /><form className="mt-5 grid gap-4 lg:grid-cols-3" onSubmit={submit}><Input id="material-titulo" label="Título" value={form.titulo} required onChange={(e) => setForm({ ...form, titulo: e.target.value })} /><Select id="material-tipo" label="Tipo de material" value={form.tipo} options={['Libro', 'Revista', 'Audiovisual', 'Otro']} onChange={(tipo) => setForm({ ...form, tipo })} /><Select id="material-estado" label="Estado" value={form.estado} options={['Disponible', 'Prestado', 'No disponible']} onChange={(estado) => setForm({ ...form, estado })} /><div className="rounded-lg border-2 border-slate-300 p-4 lg:col-span-3"><h3 className="m-0 text-xl font-bold">Detalles adicionales</h3><p className="mt-1 text-slate-700">Por ejemplo: autor, ISBN, editorial o año.</p>{details.map((row, index) => <div key={index} className="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto]"><Input id={`detalle-nombre-${index}`} label="Campo" value={row.key} placeholder="autor" onChange={(e) => setDetails(details.map((item, i) => i === index ? { ...item, key: e.target.value } : item))} /><Input id={`detalle-valor-${index}`} label="Valor" value={row.value} placeholder="Nombre del autor" onChange={(e) => setDetails(details.map((item, i) => i === index ? { ...item, value: e.target.value } : item))} /><Button type="button" variant="danger" className="md:mt-10" onClick={() => setDetails(details.length === 1 ? [{ key: '', value: '' }] : details.filter((_, i) => i !== index))}>Quitar</Button></div>)}<Button className="mt-4" type="button" variant="secondary" onClick={() => setDetails([...details, { key: '', value: '' }])}>Añadir dato</Button></div><Actions editing={Boolean(editing)} onCancel={reset} createText="Crear material" editText="Guardar cambios del material" /></form><RecordList title="Materiales registrados" empty="No hay materiales registrados." items={items.map((item) => <li key={item.id} className="flex flex-col gap-3 border-b-2 border-slate-200 py-4 sm:flex-row sm:items-center sm:justify-between"><span><strong>{item.titulo}</strong><br /><span className="text-slate-700">{item.tipo} · {item.estado}</span></span><div className="flex gap-3"><Button variant="secondary" onClick={() => beginEdit(item)}>Editar</Button><Button variant="danger" onClick={() => void mutate('Material eliminado.', () => deleteMaterial(item.id))}>Eliminar</Button></div></li>)} /></Card>
}

function MiembroManager({ items, mutate }: { items: AdminMiembro[]; mutate: Mutate }) {
  const [editing, setEditing] = useState<AdminMiembro | null>(null); const [form, setForm] = useState<MiembroInput>(blankMiembro); const reset = () => { setEditing(null); setForm(blankMiembro) }
  const submit = async (event: FormEvent) => { event.preventDefault(); await mutate(editing ? 'Miembro actualizado correctamente.' : 'Miembro creado correctamente.', () => editing ? updateMiembro(editing.id, form) : createMiembro(form)); reset() }
  return <Card aria-labelledby="miembros-title"><Title id="miembros-title" text="Gestión de miembros" description="Registre y actualice a las personas que usan la biblioteca." /><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={submit}><Input id="miembro-nombre" label="Nombre completo" required value={form.nombre_completo} onChange={(e) => setForm({ ...form, nombre_completo: e.target.value })} /><Input id="miembro-codigo" label="DNI o código" required value={form.codigo} onChange={(e) => setForm({ ...form, codigo: e.target.value })} /><Input id="miembro-tipo" label="Tipo de miembro" required value={form.tipo} placeholder="Ejemplo: Estudiante" onChange={(e) => setForm({ ...form, tipo: e.target.value })} /><Input id="miembro-contacto" label="Contacto" value={form.contacto ?? ''} placeholder="Teléfono o correo" onChange={(e) => setForm({ ...form, contacto: e.target.value })} /><Actions editing={Boolean(editing)} onCancel={reset} createText="Crear miembro" editText="Guardar cambios del miembro" /></form><RecordList title="Miembros registrados" empty="No hay miembros registrados." items={items.map((item) => <li key={item.id} className="flex flex-col gap-3 border-b-2 border-slate-200 py-4 sm:flex-row sm:items-center sm:justify-between"><span><strong>{item.nombre_completo}</strong><br /><span className="text-slate-700">{item.codigo} · {item.tipo}</span></span><div className="flex gap-3"><Button variant="secondary" onClick={() => { setEditing(item); setForm({ nombre_completo: item.nombre_completo, tipo: item.tipo, codigo: item.codigo, contacto: item.contacto }) }}>Editar</Button><Button variant="danger" onClick={() => void mutate('Miembro eliminado.', () => deleteMiembro(item.id))}>Eliminar</Button></div></li>)} /></Card>
}

function PerfilManager({ items, ownId, mutate }: { items: AdminPerfil[]; ownId: string; mutate: Mutate }) {
  const [editing, setEditing] = useState<AdminPerfil | null>(null); const [form, setForm] = useState(blankPerfil); const reset = () => { setEditing(null); setForm(blankPerfil) }
  const submit = async (event: FormEvent) => { event.preventDefault(); await mutate(editing ? 'Perfil actualizado correctamente.' : 'Perfil creado correctamente.', () => editing ? updatePerfil(editing.id, { nombre: form.nombre, rol: form.rol }) : createPerfil(form)); reset() }
  return <Card aria-labelledby="personal-title"><Title id="personal-title" text="Gestión de personal" description="Administre los perfiles con acceso al sistema." /><form className="mt-5 grid gap-4 md:grid-cols-3" onSubmit={submit}><Input id="perfil-id" label="ID de cuenta" required disabled={Boolean(editing)} value={form.id} helpText="Debe coincidir con el ID de Auth de Supabase." onChange={(e) => setForm({ ...form, id: e.target.value })} /><Input id="perfil-nombre" label="Nombre" required value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} /><Select id="perfil-rol" label="Rol" value={form.rol} options={['Administrador', 'Bibliotecario']} onChange={(rol) => setForm({ ...form, rol: rol as 'Administrador' | 'Bibliotecario' })} /><Actions editing={Boolean(editing)} onCancel={reset} createText="Crear perfil" editText="Guardar cambios del perfil" /></form><RecordList title="Personal registrado" empty="No hay perfiles registrados." items={items.map((item) => <li key={item.id} className="flex flex-col gap-3 border-b-2 border-slate-200 py-4 sm:flex-row sm:items-center sm:justify-between"><span><strong>{item.nombre}</strong><br /><span className="text-slate-700">{item.rol}</span></span><div className="flex gap-3"><Button variant="secondary" onClick={() => { setEditing(item); setForm(item) }}>Editar</Button>{item.id !== ownId && <Button variant="danger" onClick={() => void mutate('Perfil eliminado.', () => deletePerfil(item.id))}>Eliminar</Button>}</div></li>)} /></Card>
}

function Title({ id, text, description }: { id: string; text: string; description: string }) { return <><h2 id={id} className="m-0 text-2xl font-bold">{text}</h2><p className="mt-1 text-slate-700">{description}</p></> }
function Select({ id, label, value, options, onChange }: { id: string; label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <div><label className="mb-2 block font-bold" htmlFor={id}>{label}</label><select id={id} value={value} onChange={(e) => onChange(e.target.value)} className="min-h-touch w-full rounded-lg border-2 border-slate-700 bg-white px-4 py-3 text-lg">{options.map((option) => <option key={option}>{option}</option>)}</select></div> }
function Actions({ editing, onCancel, createText, editText }: { editing: boolean; onCancel: () => void; createText: string; editText: string }) { return <div className="flex flex-col gap-3 md:col-span-3 sm:flex-row"><Button className="flex-1" type="submit">{editing ? editText : createText}</Button>{editing && <Button type="button" variant="secondary" onClick={onCancel}>Cancelar edición</Button>}</div> }
function RecordList({ title, empty, items }: { title: string; empty: string; items: React.ReactNode[] }) { return <section className="mt-8" aria-label={title}><h3 className="text-xl font-bold">{title}</h3>{items.length ? <ul className="m-0 list-none p-0">{items}</ul> : <p className="rounded-lg bg-slate-100 p-4">{empty}</p>}</section> }
function AdminSkeleton() { return <div className="mt-6 space-y-8" role="status" aria-label="Cargando administración">{[1, 2, 3].map((item) => <div key={item} className="card animate-pulse"><div className="h-8 w-1/3 rounded bg-slate-300" /><div className="mt-5 h-14 rounded bg-slate-200" /><div className="mt-4 h-14 rounded bg-slate-200" /></div>)}<span className="sr-only">Cargando información administrativa…</span></div> }
